<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Smalot\\Magento\\' => array($vendorDir . '/smalot/magento-client/src'),
    'Sabberworm\\CSS' => array($vendorDir . '/sabberworm/php-css-parser/lib'),
    'Cagartner\\CorreiosConsulta' => array($vendorDir . '/cagartner/correios-consulta/src'),
);
